/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//made by MSD
package GI;

import Control.PrClientes;
import Control.PrProductos;
import Control.PrStock;
import Modelo.productos;
import Modelo.stock;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author salom
 */
public class frmProductos extends javax.swing.JFrame {

    /**
     * Creates new form frmProductos
     */
    private String nombre;
    PrStock objs=new PrStock();
    PrProductos objp=new PrProductos();
    PrClientes objc=new PrClientes();
    public frmProductos() {
        initComponents();
        imagenes();
        this.setTitle("Productos");
        this.setIconImage(new ImageIcon(getClass().getResource("/img/productos.png")).getImage());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblImagenClancy = new javax.swing.JLabel();
        lblTopPrecio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblImagenRab = new javax.swing.JLabel();
        chkTop = new javax.swing.JCheckBox();
        cbxCantidad1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lblRabPrecio = new javax.swing.JLabel();
        chkRab = new javax.swing.JCheckBox();
        cbxCantidad2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lblTheSPRecio = new javax.swing.JLabel();
        chkThestrokes = new javax.swing.JCheckBox();
        lblImagenThestrokes = new javax.swing.JLabel();
        cbxCantidad3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        lblLuisPrecio = new javax.swing.JLabel();
        chkLuis = new javax.swing.JCheckBox();
        cbxCantidad4 = new javax.swing.JComboBox<>();
        lblImagenLuis = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Music Shop");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nuevos lanzamientos");

        jLabel3.setText("Twenty One Pilots - Clancy");

        lblTopPrecio.setText("249");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Mas comprados");

        chkTop.setText("Agregar al carrito");
        chkTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkTopMouseClicked(evt);
            }
        });

        cbxCantidad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel6.setText("Twenty One Pilots - Regional At Best");

        lblRabPrecio.setText("800");

        chkRab.setText("Agregar al carrito");
        chkRab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRabActionPerformed(evt);
            }
        });

        cbxCantidad2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel8.setText("The strokes - The new Abnormal");

        lblTheSPRecio.setText("289");

        chkThestrokes.setText("Agregar al carrito");

        cbxCantidad3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel10.setText("Luins Miguel - Romances");

        lblLuisPrecio.setText("129");

        chkLuis.setText("Agregar al carrito");

        cbxCantidad4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnComprar.setBackground(new java.awt.Color(119, 221, 119));
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        jLabel4.setText("$");

        jLabel7.setText("$");

        jLabel9.setText("$");

        jLabel11.setText("$");

        btnRegresar.setBackground(new java.awt.Color(132, 182, 244));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblTheSPRecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(cbxCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(chkThestrokes))))
                                .addGap(18, 18, 18)
                                .addComponent(lblImagenThestrokes, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkTop)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblTopPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(80, 80, 80)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(cbxCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addComponent(lblImagenClancy, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRabPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbxCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkRab))
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(48, 48, 48)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImagenRab, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblLuisPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(cbxCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chkLuis))
                                .addGap(18, 18, 18)
                                .addComponent(lblImagenLuis, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(265, 265, 265)
                        .addComponent(btnRegresar)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(809, 809, 809))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(btnComprar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnRegresar)))
                .addGap(14, 14, 14)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRabPrecio)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkRab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblImagenClancy, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTopPrecio)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(chkTop)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(lblImagenRab, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTheSPRecio)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkThestrokes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(jLabel10)
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblLuisPrecio)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chkLuis, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblImagenLuis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblImagenThestrokes, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(btnComprar)
                        .addGap(111, 111, 111))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        if(chkTop.isSelected()||chkRab.isSelected()||chkThestrokes.isSelected()||chkLuis.isSelected()){
            compra();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Tienes que seleccionar al menos un producto a la venta");
        }
        
    }//GEN-LAST:event_btnComprarActionPerformed

    private void chkTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkTopMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTopMouseClicked

    private void chkRabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRabActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Main regresar=new Main();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxCantidad1;
    private javax.swing.JComboBox<String> cbxCantidad2;
    private javax.swing.JComboBox<String> cbxCantidad3;
    private javax.swing.JComboBox<String> cbxCantidad4;
    private javax.swing.JCheckBox chkLuis;
    private javax.swing.JCheckBox chkRab;
    private javax.swing.JCheckBox chkThestrokes;
    private javax.swing.JCheckBox chkTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagenClancy;
    private javax.swing.JLabel lblImagenLuis;
    private javax.swing.JLabel lblImagenRab;
    private javax.swing.JLabel lblImagenThestrokes;
    private javax.swing.JLabel lblLuisPrecio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRabPrecio;
    private javax.swing.JLabel lblTheSPRecio;
    private javax.swing.JLabel lblTopPrecio;
    // End of variables declaration//GEN-END:variables
    private void imagenes(){
        Icon imgClancy =new ImageIcon(new ImageIcon(getClass().getResource("/img/clancy.jpg")).getImage().getScaledInstance(lblImagenClancy.getWidth(), lblImagenClancy.getHeight(), WIDTH));
        lblImagenClancy.setIcon(imgClancy);
        Icon imgLuis=new ImageIcon(new ImageIcon(getClass().getResource("/img/romances.jpg")).getImage().getScaledInstance(lblImagenLuis.getWidth(), lblImagenClancy.getHeight(), WIDTH));
        lblImagenLuis.setIcon(imgLuis);
        Icon imgRab=new ImageIcon(new ImageIcon(getClass().getResource("/img/rab.jpg")).getImage().getScaledInstance(lblImagenRab.getWidth(), lblImagenRab.getHeight(), WIDTH));
        lblImagenRab.setIcon(imgRab);
        Icon imgThestrokes = new ImageIcon(new ImageIcon(getClass().getResource("/img/thenew.jpg")).getImage().getScaledInstance(lblImagenThestrokes.getWidth(), lblImagenThestrokes.getHeight(), WIDTH));
        lblImagenThestrokes.setIcon(imgThestrokes);
    }
    public void nombremostrado(String nombre){
        this.nombre=nombre;
        lblNombre.setText(nombre);
    }
    private void compra(){
        int disco1=0,disco2=0,disco3=0,disco4=0,total=0;
        int c1 = 0,c2=0,c3=0,c4=0;
        if(chkTop.isSelected()){
            disco1=Integer.parseInt(lblTopPrecio.getText())*Integer.parseInt(cbxCantidad1.getSelectedItem().toString());
            c1=Integer.parseInt(cbxCantidad1.getSelectedItem().toString());
            stockClancy(c1);
        }
        if(chkRab.isSelected()){
            disco2=Integer.parseInt(lblRabPrecio.getText())*Integer.parseInt(cbxCantidad2.getSelectedItem().toString());
            c2=Integer.parseInt(cbxCantidad2.getSelectedItem().toString());
            stockRab(c2);
        }
        if(chkThestrokes.isSelected()){
            disco3=Integer.parseInt(lblTheSPRecio.getText())*Integer.parseInt(cbxCantidad3.getSelectedItem().toString());
            c3=Integer.parseInt(cbxCantidad3.getSelectedItem().toString());
            stockThe(c3);
        }
        if(chkLuis.isSelected()){
            disco4=Integer.parseInt(lblLuisPrecio.getText())*Integer.parseInt(cbxCantidad4.getSelectedItem().toString());
            c4=Integer.parseInt(cbxCantidad4.getSelectedItem().toString());
            stockLuis(c4);
        }
        
        total=disco1+disco2+disco3+disco4;
        int compradiscos=c1+c2+c3+c4;
        String totals=String.valueOf(total);
        String nom=lblNombre.getText();
        String compra=String.valueOf(compradiscos);
        productos obje=new productos(nom,compra,totals);
        try{
            objp.insertar(obje);
            JOptionPane.showMessageDialog(rootPane, "Compra realizada correctamente "+nom+" compraste: "+"\n"+compradiscos+"discos que es un total de: " +total);
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, "Error insertar los datos: "+e.getMessage());
        }
    }
    public void escribirActualizado(ArrayList<stock> stock)throws IOException{
        FileWriter fw=new FileWriter("Documentos\\BD_STOCK.txt",false);
        for(stock e:stock){
            String cad=e.getDisco()+"-"+e.getCantidad();
            fw.write(cad);
            fw.write(10);
        }
        fw.close();
    }
    private void stockClancy(int disco_res){
        int rest=disco_res;
        int newtotal=0;
        try{
            objs.leer();
            ArrayList<stock> actualizacion=new ArrayList<>();
            for(stock e:objs.array){
                if(e.getDisco().equals("Clancy")){
                newtotal=Integer.parseInt(e.getCantidad())-rest;
                e.setDisco("Clancy");
                e.setCantidad(String.valueOf(newtotal));
                }
                actualizacion.add(e);
            }
            escribirActualizado(actualizacion);
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        
        }
    }
    private void stockRab(int disco_res){
        int rest=disco_res;
        int newtotal=0;
        try{
            objs.leer();
            ArrayList<stock> actualizacion=new ArrayList<>();
            for(stock e:objs.array){
                if(e.getDisco().equals("Rab")){
                newtotal=Integer.parseInt(e.getCantidad())-rest;
                e.setDisco("Rab");
                e.setCantidad(String.valueOf(newtotal));
                }
                actualizacion.add(e);
            }
            escribirActualizado(actualizacion);
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        
        }
    }
    private void stockThe(int disco_res){
        int rest=disco_res;
        int newtotal=0;
        try{
            objs.leer();
            ArrayList<stock> actualizacion=new ArrayList<>();
            for(stock e:objs.array){
                if(e.getDisco().equals("Tna")){
                newtotal=Integer.parseInt(e.getCantidad())-rest;
                e.setDisco("Tna");
                e.setCantidad(String.valueOf(newtotal));
                }
                actualizacion.add(e);
            }
            escribirActualizado(actualizacion);
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        
        }
    }
    private void stockLuis(int disco_res){
        int rest=disco_res;
        int newtotal=0;
        try{
            objs.leer();
            ArrayList<stock> actualizacion=new ArrayList<>();
            for(stock e:objs.array){
                if(e.getDisco().equals("Romances")){
                newtotal=Integer.parseInt(e.getCantidad())-rest;
                e.setDisco("Romances");
                e.setCantidad(String.valueOf(newtotal));
                }
                actualizacion.add(e);
            }
            escribirActualizado(actualizacion);
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        
        }
    }
}
